name: Build and Upload JAR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: openjdk:17-slim

    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'Kotlin/kotlin-spec'
          path: 'kotlin-spec'

      - uses: actions/checkout@v2
        with:
          repository: 'iyubondyrev/KotlinTokenizerJB'
          path: 'KotlinTokenizerJB'

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Git
        run: |
          apt-get update
          apt-get install -y git

      - name: Install kotlin-grammar-parser
        run: |
          cd kotlin-spec
          ./gradlew :grammar:publishToMavenLocal

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: KotlinTokenizerJB

      - name: Build and Publish to Maven Local
        run: ./gradlew publishToMavenLocal
        working-directory: KotlinTokenizerJB

      - name: Build Tokenizer JAR
        run: ./gradlew TokenizerJar
        working-directory: KotlinTokenizerJB

      - name: Build GetPopularLiterals JAR
        run: ./gradlew GetPopularLiteralsJar
        working-directory: KotlinTokenizerJB

      - name: Upload JAR to GitHub Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: My-Kotlin-Jars
          path: build/libs/*.jar
        working-directory: KotlinTokenizerJB
