name: Build and Upload JAR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: openjdk:17

    steps:
      - uses: actions/checkout@v2

      - name: Install Git
        run: apt-get update && apt-get install -y git

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Clone Kotlin specification
        run: git clone https://github.com/Kotlin/kotlin-spec.git

      - name: Install kotlin-grammar-parser
        run: |
          cd kotlin-spec
          ./gradlew :grammar:publishToMavenLocal

      - name: Build and Publish to Maven Local
        run: ./gradlew publishToMavenLocal

      - name: Build Tokenizer JAR
        run: ./gradlew TokenizerJar

      - name: Build GetPopularLiterals JAR
        run: ./gradlew GetPopularLiteralsJar


      - name: Upload JAR to GitHub Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: My-Kotlin-Jars
          path: build/libs/*.jar
